[2024-08-12T17:16:40.310+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quarterly_retrain.optimize_and_register_best_classifier manual__2024-08-12T17:16:34.875723+00:00 [queued]>
[2024-08-12T17:16:40.313+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quarterly_retrain.optimize_and_register_best_classifier manual__2024-08-12T17:16:34.875723+00:00 [queued]>
[2024-08-12T17:16:40.314+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T17:16:40.319+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): optimize_and_register_best_classifier> on 2024-08-12 17:16:34.875723+00:00
[2024-08-12T17:16:40.324+0000] {standard_task_runner.py:57} INFO - Started process 915 to run task
[2024-08-12T17:16:40.328+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'quarterly_retrain', 'optimize_and_register_best_classifier', 'manual__2024-08-12T17:16:34.875723+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/quarterly_retrain.py', '--cfg-path', '/tmp/tmpq9oaip59']
[2024-08-12T17:16:40.328+0000] {standard_task_runner.py:85} INFO - Job 184: Subtask optimize_and_register_best_classifier
[2024-08-12T17:16:40.354+0000] {task_command.py:415} INFO - Running <TaskInstance: quarterly_retrain.optimize_and_register_best_classifier manual__2024-08-12T17:16:34.875723+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T17:16:41.638+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='quarterly_retrain' AIRFLOW_CTX_TASK_ID='optimize_and_register_best_classifier' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T17:16:34.875723+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-12T17:16:34.875723+00:00'
[2024-08-12T17:16:41.755+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/quarterly_retrain.py", line 156, in optimize_and_register_best_classifier
    model_type = find_best_classifier(client, experiment_name)
  File "/opt/airflow/dags/quarterly_retrain.py", line 41, in find_best_classifier
    best_run = client.search_runs(
IndexError: list index out of range
[2024-08-12T17:16:41.774+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=quarterly_retrain, task_id=optimize_and_register_best_classifier, execution_date=20240812T171634, start_date=20240812T171640, end_date=20240812T171641
[2024-08-12T17:16:41.795+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 184 for task optimize_and_register_best_classifier (list index out of range; 915)
[2024-08-12T17:16:41.852+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T17:16:41.886+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
