[2024-08-12T18:14:03.356+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-08-12T18:14:03.474+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-08-12T18:14:03.478+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T18:14:03.512+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-05-01 00:00:00+00:00
[2024-08-12T18:14:03.583+0000] {standard_task_runner.py:57} INFO - Started process 9396 to run task
[2024-08-12T18:14:03.609+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-05-01T00:00:00+00:00', '--job-id', '281', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmp66q_3i5k']
[2024-08-12T18:14:03.617+0000] {standard_task_runner.py:85} INFO - Job 281: Subtask insert_data
[2024-08-12T18:14:03.850+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T18:14:04.129+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T00:00:00+00:00'
[2024-08-12T18:14:04.187+0000] {logging_mixin.py:151} INFO - inserted data for 2024-04-30
[2024-08-12T18:14:04.203+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T18:14:04.283+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240501T000000, start_date=20240812T181403, end_date=20240812T181404
[2024-08-12T18:14:04.419+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T18:14:04.690+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T19:22:15.885+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-08-12T19:22:15.902+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-08-12T19:22:15.903+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T19:22:15.932+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-05-01 00:00:00+00:00
[2024-08-12T19:22:15.943+0000] {standard_task_runner.py:57} INFO - Started process 4399 to run task
[2024-08-12T19:22:15.952+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-05-01T00:00:00+00:00', '--job-id', '500', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmp6goh6fnk']
[2024-08-12T19:22:15.970+0000] {standard_task_runner.py:85} INFO - Job 500: Subtask insert_data
[2024-08-12T19:22:16.081+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T19:22:16.247+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T00:00:00+00:00'
[2024-08-12T19:22:16.255+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monitor.py", line 133, in insert_data
    cur.execute(insert_statement, data)
psycopg2.errors.UndefinedColumn: column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^

[2024-08-12T19:22:16.267+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240501T000000, start_date=20240812T192215, end_date=20240812T192216
[2024-08-12T19:22:16.278+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 500 for task insert_data (column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^
; 4399)
[2024-08-12T19:22:16.306+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T19:22:16.323+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T19:27:23.104+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-08-12T19:27:23.118+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-08-12T19:27:23.118+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T19:27:23.249+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-05-01 00:00:00+00:00
[2024-08-12T19:27:23.260+0000] {standard_task_runner.py:57} INFO - Started process 5392 to run task
[2024-08-12T19:27:23.271+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-05-01T00:00:00+00:00', '--job-id', '547', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmpfwsg090b']
[2024-08-12T19:27:23.282+0000] {standard_task_runner.py:85} INFO - Job 547: Subtask insert_data
[2024-08-12T19:27:23.423+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T19:27:23.583+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T00:00:00+00:00'
[2024-08-12T19:27:23.613+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monitor.py", line 133, in insert_data
    cur.execute(insert_statement, data)
psycopg2.errors.UndefinedColumn: column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^

[2024-08-12T19:27:23.655+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240501T000000, start_date=20240812T192723, end_date=20240812T192723
[2024-08-12T19:27:23.816+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 547 for task insert_data (column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^
; 5392)
[2024-08-12T19:27:23.901+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T19:27:23.935+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T19:28:44.541+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-08-12T19:28:44.546+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-08-12T19:28:44.546+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T19:28:44.553+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-05-01 00:00:00+00:00
[2024-08-12T19:28:44.562+0000] {standard_task_runner.py:57} INFO - Started process 5890 to run task
[2024-08-12T19:28:44.565+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-05-01T00:00:00+00:00', '--job-id', '590', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmpgxgnxjaf']
[2024-08-12T19:28:44.569+0000] {standard_task_runner.py:85} INFO - Job 590: Subtask insert_data
[2024-08-12T19:28:44.601+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T19:28:44.656+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T00:00:00+00:00'
[2024-08-12T19:28:44.662+0000] {logging_mixin.py:151} INFO - inserted data for 2024-04-30
[2024-08-12T19:28:44.662+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T19:28:44.670+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240501T000000, start_date=20240812T192844, end_date=20240812T192844
[2024-08-12T19:28:44.702+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T19:28:44.720+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T20:10:14.095+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-08-12T20:10:14.162+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-08-12T20:10:14.178+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T20:10:14.237+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-05-01 00:00:00+00:00
[2024-08-12T20:10:14.344+0000] {standard_task_runner.py:57} INFO - Started process 13206 to run task
[2024-08-12T20:10:14.390+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-05-01T00:00:00+00:00', '--job-id', '915', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmppz3yoo35']
[2024-08-12T20:10:14.413+0000] {standard_task_runner.py:85} INFO - Job 915: Subtask insert_data
[2024-08-12T20:10:14.682+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-05-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T20:10:15.119+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T00:00:00+00:00'
[2024-08-12T20:10:15.160+0000] {logging_mixin.py:151} INFO - inserted data for 2024-04-30
[2024-08-12T20:10:15.162+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T20:10:15.196+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240501T000000, start_date=20240812T201014, end_date=20240812T201015
[2024-08-12T20:10:15.269+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T20:10:15.408+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
