[2024-08-12T18:14:03.930+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-08-12T18:14:04.004+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-08-12T18:14:04.019+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T18:14:04.090+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-06-01 00:00:00+00:00
[2024-08-12T18:14:04.143+0000] {standard_task_runner.py:57} INFO - Started process 9399 to run task
[2024-08-12T18:14:04.157+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-06-01T00:00:00+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmph6bb2w0r']
[2024-08-12T18:14:04.187+0000] {standard_task_runner.py:85} INFO - Job 282: Subtask insert_data
[2024-08-12T18:14:04.573+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T18:14:05.020+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T00:00:00+00:00'
[2024-08-12T18:14:05.043+0000] {logging_mixin.py:151} INFO - inserted data for 2024-05-31
[2024-08-12T18:14:05.051+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T18:14:05.099+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240601T000000, start_date=20240812T181403, end_date=20240812T181405
[2024-08-12T18:14:05.267+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T18:14:05.301+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T19:19:41.601+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-08-12T19:19:41.634+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-08-12T19:19:41.645+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T19:19:41.663+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-06-01 00:00:00+00:00
[2024-08-12T19:19:41.671+0000] {standard_task_runner.py:57} INFO - Started process 3724 to run task
[2024-08-12T19:19:41.694+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-06-01T00:00:00+00:00', '--job-id', '457', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmpkmyp3od_']
[2024-08-12T19:19:41.704+0000] {standard_task_runner.py:85} INFO - Job 457: Subtask insert_data
[2024-08-12T19:19:41.785+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T19:19:41.890+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T00:00:00+00:00'
[2024-08-12T19:19:41.900+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monitor.py", line 133, in insert_data
    cur.execute(insert_statement, data)
psycopg2.errors.UndefinedColumn: column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^

[2024-08-12T19:19:41.910+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240601T000000, start_date=20240812T191941, end_date=20240812T191941
[2024-08-12T19:19:41.917+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 457 for task insert_data (column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^
; 3724)
[2024-08-12T19:19:41.966+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T19:19:41.990+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T19:22:14.171+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-08-12T19:22:14.305+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-08-12T19:22:14.331+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T19:22:14.423+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-06-01 00:00:00+00:00
[2024-08-12T19:22:14.472+0000] {standard_task_runner.py:57} INFO - Started process 4388 to run task
[2024-08-12T19:22:14.485+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-06-01T00:00:00+00:00', '--job-id', '498', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmpzijcl2sy']
[2024-08-12T19:22:14.534+0000] {standard_task_runner.py:85} INFO - Job 498: Subtask insert_data
[2024-08-12T19:22:14.796+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T19:22:15.102+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T00:00:00+00:00'
[2024-08-12T19:22:15.129+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monitor.py", line 133, in insert_data
    cur.execute(insert_statement, data)
psycopg2.errors.UndefinedColumn: column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^

[2024-08-12T19:22:15.150+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240601T000000, start_date=20240812T192214, end_date=20240812T192215
[2024-08-12T19:22:15.172+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 498 for task insert_data (column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^
; 4388)
[2024-08-12T19:22:15.210+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T19:22:15.287+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T19:27:24.870+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-08-12T19:27:24.884+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-08-12T19:27:24.891+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T19:27:24.926+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-06-01 00:00:00+00:00
[2024-08-12T19:27:24.971+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-06-01T00:00:00+00:00', '--job-id', '554', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmp8lr1qlpc']
[2024-08-12T19:27:24.988+0000] {standard_task_runner.py:85} INFO - Job 554: Subtask insert_data
[2024-08-12T19:27:24.954+0000] {standard_task_runner.py:57} INFO - Started process 5407 to run task
[2024-08-12T19:27:25.054+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T19:27:25.165+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T00:00:00+00:00'
[2024-08-12T19:27:25.175+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monitor.py", line 133, in insert_data
    cur.execute(insert_statement, data)
psycopg2.errors.UndefinedColumn: column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^

[2024-08-12T19:27:25.188+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240601T000000, start_date=20240812T192724, end_date=20240812T192725
[2024-08-12T19:27:25.196+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 554 for task insert_data (column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^
; 5407)
[2024-08-12T19:27:25.222+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T19:27:25.237+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T19:28:42.977+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-08-12T19:28:43.026+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-08-12T19:28:43.041+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T19:28:43.087+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-06-01 00:00:00+00:00
[2024-08-12T19:28:43.112+0000] {standard_task_runner.py:57} INFO - Started process 5865 to run task
[2024-08-12T19:28:43.117+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-06-01T00:00:00+00:00', '--job-id', '583', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmp92jo6c9p']
[2024-08-12T19:28:43.139+0000] {standard_task_runner.py:85} INFO - Job 583: Subtask insert_data
[2024-08-12T19:28:43.237+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T19:28:43.407+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T00:00:00+00:00'
[2024-08-12T19:28:43.426+0000] {logging_mixin.py:151} INFO - inserted data for 2024-05-31
[2024-08-12T19:28:43.426+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T19:28:43.476+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240601T000000, start_date=20240812T192843, end_date=20240812T192843
[2024-08-12T19:28:43.529+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T19:28:43.555+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T20:10:13.627+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-08-12T20:10:13.726+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-08-12T20:10:13.748+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T20:10:13.828+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-06-01 00:00:00+00:00
[2024-08-12T20:10:13.871+0000] {standard_task_runner.py:57} INFO - Started process 13203 to run task
[2024-08-12T20:10:13.879+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-06-01T00:00:00+00:00', '--job-id', '912', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmpms09p1ai']
[2024-08-12T20:10:13.910+0000] {standard_task_runner.py:85} INFO - Job 912: Subtask insert_data
[2024-08-12T20:10:14.268+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-06-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T20:10:14.708+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T00:00:00+00:00'
[2024-08-12T20:10:14.799+0000] {logging_mixin.py:151} INFO - inserted data for 2024-05-31
[2024-08-12T20:10:14.805+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T20:10:14.840+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240601T000000, start_date=20240812T201013, end_date=20240812T201014
[2024-08-12T20:10:14.937+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T20:10:15.318+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
