[2024-08-12T18:13:58.071+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T18:13:58.194+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T18:13:58.208+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T18:13:58.306+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-04-01 00:00:00+00:00
[2024-08-12T18:13:58.421+0000] {standard_task_runner.py:57} INFO - Started process 9360 to run task
[2024-08-12T18:13:58.430+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmpttn6ppxv']
[2024-08-12T18:13:58.435+0000] {standard_task_runner.py:85} INFO - Job 276: Subtask insert_data
[2024-08-12T18:13:58.736+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T18:13:59.343+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-08-12T18:13:59.404+0000] {logging_mixin.py:151} INFO - inserted data for 2024-03-31
[2024-08-12T18:13:59.406+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T18:13:59.445+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240401T000000, start_date=20240812T181358, end_date=20240812T181359
[2024-08-12T18:13:59.532+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T18:13:59.978+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T19:22:15.923+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T19:22:15.935+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T19:22:15.936+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T19:22:15.971+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-04-01 00:00:00+00:00
[2024-08-12T19:22:15.988+0000] {standard_task_runner.py:57} INFO - Started process 4400 to run task
[2024-08-12T19:22:15.995+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '501', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmpi0nggv3p']
[2024-08-12T19:22:16.003+0000] {standard_task_runner.py:85} INFO - Job 501: Subtask insert_data
[2024-08-12T19:22:16.138+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T19:22:16.270+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-08-12T19:22:16.279+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monitor.py", line 133, in insert_data
    cur.execute(insert_statement, data)
psycopg2.errors.UndefinedColumn: column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^

[2024-08-12T19:22:16.297+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240401T000000, start_date=20240812T192215, end_date=20240812T192216
[2024-08-12T19:22:16.308+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 501 for task insert_data (column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^
; 4400)
[2024-08-12T19:22:16.350+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T19:22:16.360+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T19:27:24.022+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T19:27:24.079+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T19:27:24.088+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T19:27:24.116+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-04-01 00:00:00+00:00
[2024-08-12T19:27:24.141+0000] {standard_task_runner.py:57} INFO - Started process 5396 to run task
[2024-08-12T19:27:24.146+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '551', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmpgz6a5hwl']
[2024-08-12T19:27:24.157+0000] {standard_task_runner.py:85} INFO - Job 551: Subtask insert_data
[2024-08-12T19:27:24.276+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T19:27:24.485+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-08-12T19:27:24.492+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monitor.py", line 133, in insert_data
    cur.execute(insert_statement, data)
psycopg2.errors.UndefinedColumn: column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^

[2024-08-12T19:27:24.508+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240401T000000, start_date=20240812T192724, end_date=20240812T192724
[2024-08-12T19:27:24.548+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 551 for task insert_data (column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^
; 5396)
[2024-08-12T19:27:24.661+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T19:27:24.690+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T19:28:43.834+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T19:28:43.839+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T19:28:43.840+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T19:28:43.853+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-04-01 00:00:00+00:00
[2024-08-12T19:28:43.870+0000] {standard_task_runner.py:57} INFO - Started process 5880 to run task
[2024-08-12T19:28:43.870+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '588', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmptfrt58sy']
[2024-08-12T19:28:43.877+0000] {standard_task_runner.py:85} INFO - Job 588: Subtask insert_data
[2024-08-12T19:28:43.948+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T19:28:44.084+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-08-12T19:28:44.095+0000] {logging_mixin.py:151} INFO - inserted data for 2024-03-31
[2024-08-12T19:28:44.096+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T19:28:44.113+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240401T000000, start_date=20240812T192843, end_date=20240812T192844
[2024-08-12T19:28:44.145+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T19:28:44.170+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T20:10:15.554+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T20:10:15.569+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T20:10:15.569+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T20:10:15.637+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-04-01 00:00:00+00:00
[2024-08-12T20:10:15.657+0000] {standard_task_runner.py:57} INFO - Started process 13217 to run task
[2024-08-12T20:10:15.663+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '920', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmp__lm_cni']
[2024-08-12T20:10:15.669+0000] {standard_task_runner.py:85} INFO - Job 920: Subtask insert_data
[2024-08-12T20:10:15.780+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-04-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T20:10:15.908+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-08-12T20:10:15.919+0000] {logging_mixin.py:151} INFO - inserted data for 2024-03-31
[2024-08-12T20:10:15.919+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T20:10:15.934+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240401T000000, start_date=20240812T201015, end_date=20240812T201015
[2024-08-12T20:10:15.979+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T20:10:16.002+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
