[2024-08-12T18:14:00.073+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-08-12T18:14:00.119+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-08-12T18:14:00.126+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T18:14:00.287+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-03-01 00:00:00+00:00
[2024-08-12T18:14:00.335+0000] {standard_task_runner.py:57} INFO - Started process 9375 to run task
[2024-08-12T18:14:00.339+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-03-01T00:00:00+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmpwhkzkyoo']
[2024-08-12T18:14:00.374+0000] {standard_task_runner.py:85} INFO - Job 280: Subtask insert_data
[2024-08-12T18:14:00.743+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T18:14:01.472+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-01T00:00:00+00:00'
[2024-08-12T18:14:01.506+0000] {logging_mixin.py:151} INFO - inserted data for 2024-02-29
[2024-08-12T18:14:01.511+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T18:14:01.530+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240301T000000, start_date=20240812T181400, end_date=20240812T181401
[2024-08-12T18:14:01.608+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T18:14:01.696+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T19:22:15.199+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-08-12T19:22:15.216+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-08-12T19:22:15.218+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T19:22:15.229+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-03-01 00:00:00+00:00
[2024-08-12T19:22:15.261+0000] {standard_task_runner.py:57} INFO - Started process 4398 to run task
[2024-08-12T19:22:15.265+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-03-01T00:00:00+00:00', '--job-id', '499', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmpev5mo5vb']
[2024-08-12T19:22:15.269+0000] {standard_task_runner.py:85} INFO - Job 499: Subtask insert_data
[2024-08-12T19:22:15.418+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T19:22:15.624+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-01T00:00:00+00:00'
[2024-08-12T19:22:15.634+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monitor.py", line 133, in insert_data
    cur.execute(insert_statement, data)
psycopg2.errors.UndefinedColumn: column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^

[2024-08-12T19:22:15.662+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240301T000000, start_date=20240812T192215, end_date=20240812T192215
[2024-08-12T19:22:15.679+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 499 for task insert_data (column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^
; 4398)
[2024-08-12T19:22:15.707+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T19:22:15.746+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T19:27:24.469+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-08-12T19:27:24.481+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-08-12T19:27:24.488+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T19:27:24.504+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-03-01 00:00:00+00:00
[2024-08-12T19:27:24.522+0000] {standard_task_runner.py:57} INFO - Started process 5398 to run task
[2024-08-12T19:27:24.537+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-03-01T00:00:00+00:00', '--job-id', '552', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmpv16_lmvh']
[2024-08-12T19:27:24.548+0000] {standard_task_runner.py:85} INFO - Job 552: Subtask insert_data
[2024-08-12T19:27:24.708+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T19:27:24.990+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-01T00:00:00+00:00'
[2024-08-12T19:27:24.997+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monitor.py", line 133, in insert_data
    cur.execute(insert_statement, data)
psycopg2.errors.UndefinedColumn: column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^

[2024-08-12T19:27:25.010+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240301T000000, start_date=20240812T192724, end_date=20240812T192725
[2024-08-12T19:27:25.018+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 552 for task insert_data (column "share_of_drifted_columns" of relation "monitor_metrics" does not exist
LINE 6:             share_of_drifted_columns
                    ^
; 5398)
[2024-08-12T19:27:25.072+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T19:27:25.091+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T19:28:43.482+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-08-12T19:28:43.492+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-08-12T19:28:43.492+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T19:28:43.520+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-03-01 00:00:00+00:00
[2024-08-12T19:28:43.539+0000] {standard_task_runner.py:57} INFO - Started process 5875 to run task
[2024-08-12T19:28:43.546+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-03-01T00:00:00+00:00', '--job-id', '586', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmpg09ie5sm']
[2024-08-12T19:28:43.555+0000] {standard_task_runner.py:85} INFO - Job 586: Subtask insert_data
[2024-08-12T19:28:43.616+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T19:28:43.755+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-01T00:00:00+00:00'
[2024-08-12T19:28:43.767+0000] {logging_mixin.py:151} INFO - inserted data for 2024-02-29
[2024-08-12T19:28:43.767+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T19:28:43.779+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240301T000000, start_date=20240812T192843, end_date=20240812T192843
[2024-08-12T19:28:43.820+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T19:28:43.857+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T20:10:14.378+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-08-12T20:10:14.420+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-08-12T20:10:14.429+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T20:10:14.506+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_data> on 2024-03-01 00:00:00+00:00
[2024-08-12T20:10:14.561+0000] {standard_task_runner.py:57} INFO - Started process 13208 to run task
[2024-08-12T20:10:14.562+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'insert_data', 'scheduled__2024-03-01T00:00:00+00:00', '--job-id', '916', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmp241k55ej']
[2024-08-12T20:10:14.583+0000] {standard_task_runner.py:85} INFO - Job 916: Subtask insert_data
[2024-08-12T20:10:14.904+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.insert_data scheduled__2024-03-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T20:10:15.256+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-01T00:00:00+00:00'
[2024-08-12T20:10:15.270+0000] {logging_mixin.py:151} INFO - inserted data for 2024-02-29
[2024-08-12T20:10:15.272+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T20:10:15.285+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=monthly_monitor, task_id=insert_data, execution_date=20240301T000000, start_date=20240812T201014, end_date=20240812T201015
[2024-08-12T20:10:15.330+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T20:10:15.406+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
