[2024-08-12T05:52:14.560+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_monthly_data.load_model manual__2024-08-12T05:52:12.863184+00:00 [queued]>
[2024-08-12T05:52:14.567+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_monthly_data.load_model manual__2024-08-12T05:52:12.863184+00:00 [queued]>
[2024-08-12T05:52:14.568+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T05:52:14.574+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): load_model> on 2024-08-12 05:52:12.863184+00:00
[2024-08-12T05:52:14.581+0000] {standard_task_runner.py:57} INFO - Started process 4851 to run task
[2024-08-12T05:52:14.586+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'generate_monthly_data', 'load_model', 'manual__2024-08-12T05:52:12.863184+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/monthly_prediction.py', '--cfg-path', '/tmp/tmpp99nujw1']
[2024-08-12T05:52:14.587+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask load_model
[2024-08-12T05:52:14.618+0000] {task_command.py:415} INFO - Running <TaskInstance: generate_monthly_data.load_model manual__2024-08-12T05:52:12.863184+00:00 [running]> on host fa284eed0508
[2024-08-12T05:52:14.662+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generate_monthly_data' AIRFLOW_CTX_TASK_ID='load_model' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T05:52:12.863184+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-12T05:52:12.863184+00:00'
[2024-08-12T05:52:14.718+0000] {logging_mixin.py:151} INFO - gs://mlflow-artifacts-bt/1/fab1118790cd421ab4d4d45e0b254b51/artifacts/models
[2024-08-12T05:52:15.165+0000] {logging_mixin.py:151} WARNING - Downloading artifacts:   0%|          | 0/9 [00:00<?, ?it/s]
[2024-08-12T05:52:15.189+0000] {logging_mixin.py:151} WARNING - Downloading artifacts:  11%|#1        | 1/9 [00:00<00:00, 42.27it/s]
[2024-08-12T05:52:15.190+0000] {logging_mixin.py:151} WARNING - Downloading artifacts:  22%|##2       | 2/9 [00:00<00:00, 81.21it/s]
[2024-08-12T05:52:15.219+0000] {logging_mixin.py:151} WARNING - Downloading artifacts:  33%|###3      | 3/9 [00:00<00:00, 56.50it/s]
[2024-08-12T05:52:15.258+0000] {logging_mixin.py:151} WARNING - Downloading artifacts:  44%|####4     | 4/9 [00:00<00:00, 43.30it/s]
[2024-08-12T05:52:15.259+0000] {logging_mixin.py:151} WARNING - Downloading artifacts:  56%|#####5    | 5/9 [00:00<00:00, 53.58it/s]
[2024-08-12T05:52:15.260+0000] {logging_mixin.py:151} WARNING - Downloading artifacts:  67%|######6   | 6/9 [00:00<00:00, 63.84it/s]
[2024-08-12T05:52:15.267+0000] {logging_mixin.py:151} WARNING - Downloading artifacts:  78%|#######7  | 7/9 [00:00<00:00, 69.26it/s]
[2024-08-12T05:52:15.268+0000] {logging_mixin.py:151} WARNING - Downloading artifacts:  78%|#######7  | 7/9 [00:00<00:00, 69.26it/s]
[2024-08-12T05:52:15.270+0000] {logging_mixin.py:151} WARNING - Downloading artifacts:  89%|########8 | 8/9 [00:00<00:00, 69.26it/s]
[2024-08-12T05:52:16.213+0000] {logging_mixin.py:151} WARNING - Downloading artifacts: 100%|##########| 9/9 [00:01<00:00, 69.26it/s]
[2024-08-12T05:52:16.214+0000] {logging_mixin.py:151} WARNING - Downloading artifacts: 100%|##########| 9/9 [00:01<00:00,  8.58it/s]
[2024-08-12T05:52:16.373+0000] {logging_mixin.py:151} INFO - RandomForestClassifier version 1 loaded
[2024-08-12T05:52:16.373+0000] {python.py:194} INFO - Done. Returned value was: mlflow.pyfunc.loaded_model:
  artifact_path: models
  flavor: mlflow.sklearn
  run_id: fab1118790cd421ab4d4d45e0b254b51

[2024-08-12T05:52:16.378+0000] {xcom.py:661} ERROR - Object of type PyFuncModel is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-08-12T05:52:16.379+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 178, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'mlflow.pyfunc.PyFuncModel'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2477, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PyFuncModel is not JSON serializable
[2024-08-12T05:52:16.386+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=generate_monthly_data, task_id=load_model, execution_date=20240812T055212, start_date=20240812T055214, end_date=20240812T055216
[2024-08-12T05:52:16.393+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 83 for task load_model (Object of type PyFuncModel is not JSON serializable; 4851)
[2024-08-12T05:52:16.424+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T05:52:16.436+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
